# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e844223bbccb718e9a494a6afdc8330c17bf5cc86324554e80fdb45e78fcc5f9ccf06797820f3a6091b9d2d3f573749b8edf0b258c1d50c794f9e3b934633d3c

test:
  secret_key_base: 4683639b6fa0e0d6781ab0780686998506c23d7aabaca78c3ce0aa91ac3bf72707552e7bcd4d0f07c44eae953418de842b8d7d00adbdad44a8afcabd8a674996

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
